name: CML Docker-K8s Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t iris-api ./app

    - name: Tag & Push Image to GCP Artifact Registry
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE_NAME: iris-api
        REGION: us-central1
        REPO_NAME: iris-repo
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcloud.json
        gcloud auth activate-service-account --key-file=gcloud.json
        gcloud config set project $GCP_PROJECT_ID
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker tag iris-api us-central1-docker.pkg.dev/rare-keep-460211-q6/iris-repo/iris-api:latest
        docker push us-central1-docker.pkg.dev/rare-keep-460211-q6/iris-repo/iris-api:latest

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials iris-cluster --region us-central1
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml